// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmqpooctaxpfqdfywuma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtcXBvb2N0YXhwZnFkZnl3dW1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MDg3NDYsImV4cCI6MjA2MjM4NDc0Nn0.oJtQ20ccXPmGDZjY_YrNjiFLfG_8xmqr6J1nMtvI3ek";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);